### ISSUE TITLE
Share Map Page의 UI 및 기능적 디테일을 수정한다

### ISSUE THREAD

**Issue by santaiscoming** [My-Own-Weapon/wagu-front#104]
## Map page

map에 표시되는 store에 대한 ping의 이미지를 수정합니다

## Share page

user의 프로필 사진이 움직이도록 변경합니다
user의 움직임이 끊김없이 표시되도록 변경합니다
프로필이 없는 경우도 있으니 border의 색을 통해 user를 구분할 수 있도록 변경합니다

투표를 시작하고 결과까지 RTC session이 유지되어 음성통화가 유지되도록 수정합니다

### ✅ Todos

- Map page
  - [x]  store ping 이미지 수정 (Kakao map)
- Share page
  - [ ] User의 프로필 사진을 ping으로 표시한다
  - [ ] User의 프로필 사진이 없을 수 있으므로 고유한 border color를 부여한다
  - [ ] 투표결과까지 session을 유지한다
  - [ ] 유저의 움직임이 끊김이 없이 표시되게 만들어야한다
