### ISSUE TITLE
[! Important] 헥사고날 아키텍쳐를 모방한 클린 아키텍처를 적용한다.

### ISSUE THREAD

**Issue by santaiscoming** [My-Own-Weapon/wagu-front#163]
### 🔨 Describe

# 필요성

## 1. 서버의 스키마 변경이 프론트 UI에 영향을 미침

현재는 서버의 스키마를 그대로 ui로직에 녹여내고 있습니다.
이는 서버의 스키마가 변경될시에 ui도 변경되어야합니다.

이를 방지하기위해 서버의 스키마와 프론트의 ui에 사용되는 스키마의 의존성을 끊어내기 위함입니다.

### 해결방안
프론트 UI에서 사용되는 params를 필요할시에(서버에서 설정한 변수가 의도를 못드러냄) 변경합니다.
그리고 React Query의 query 및 mutation을 래핑한 hook을 만들고 해당 훅에서 서버 스키마에 해당하는 변환작업을 거칩니다.

단 application 계층이 아닌 service 계층에서 변환해야합니다. application 계층에선 client(Front)에서 지정한 param(schema)를 사용하고 client에서 정한 스키마로 zod를 이용해 타입검사를 합니다.

즉, service 계층(실제 useQuery나 useMutation)을 거칠때 변환합니다

## 2. 타입 보장
서버의 스키마가 변경될때마다 type이 정의된 파일의 interface를 변경해야합니다.

또한, 서버 응답값에 대한 예외처리가 부족하여 서버 응답값이 UI까지 오더라도 옵셔널로 추론되는 경우가 너무 많습니다.

타입 보장과 함께 서버에 대한 의존성을 낮추기 위함입니다.

### 해결방안
openApi 문서인 swagger를 지원하는 우리의 프로젝트 특성상 이를 이용하려 합니다. (openApi-ts 라이브러리)

## 3. 테스트를 위한 로직 분리
현재 많은 함수들이 하나의 함수에서 여러가지 일을 하고있으며 의존성이 강하게 결합되어 e2e테스트가 아닌 이상 테스트가 쉽지 않습니다.

테스트 코드를 통해 계발단계에 빠른 피드백으로 빠른 개발속도를 낼 수 있다고 믿기에 로직분리를 위해 아키텍쳐를 적용합니다.

### ✅ Tasks

- [x] openApi-ts 에서 path기준으로 get, post, patch, delete 등 method에 해당하는 유틸리티 타입 생성
- [x] feature 나누기
- [ ] domain logic 기준 세우기
- [ ] apiSerivce라는 싱글톤 객체로 모든 api가 관리되던것을 분리
- [ ] 필요시 UI의 변수를 변경하고 의미를 드러내기
- [ ] feature별 applications, services, domain 폴더 분리
  - [x] auth
  - [ ] live
  - [ ] map
  - [ ] post
  - [ ] vote
