### ISSUE TITLE
공유 URL을 통해 들어온 경우 보는 공유 맵

### ISSUE THREAD

**Issue by KimTaeYoung0589** [My-Own-Weapon/wagu-front#46]
### 📝 Desc

'투표 URL 생성하기' 버튼을 클릭해서 생성된 URL을 통해 들어온 사람들이 보는 맵 화면

### ✅ Todos

- [x] 가게 마커 찍기
- [x] posts 보기
- [x] 음성 채팅
- [x] 가게 투표 추가
- [x] 가게 투표 삭제
- [x] 투표 시작
- [x] 나의 투표 종료
- [x] 참여자 프로필 보여주기
- [x] 마커 이미지 자신의 프로필로 설정
